### ISSUE TITLE
v1.0.2: can't run flutter pub get since webview plugin migration

### ISSUE THREAD

**Issue by LennertDefauw1** [shuftipro/Flutter-SDK#2]
Flutter version: 2.10.1
Flutter doctor: 

`[✓] Flutter (Channel unknown, 2.10.1, on Ubuntu 20.04.3 LTS 5.13.0-30-generic, locale en_US.UTF-8)
    • Flutter version 2.10.1 at /home/lennert/tools/flutter
    • Upstream repository unknown
    • Framework revision db747aa133 (13 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /home/lennert/Android/Sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /home/lennert/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7935034/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/lennert/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7935034
    • Flutter plugin version 63.2.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.0)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Pixel 6 (mobile) • 1C221FDF600K6V • android-arm64  • Android 12 (API 31)
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 96.0.4664.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available
`

Flutter pub get result including pubspec.yaml file including only   shuftipro_flutter_sdk: ^1.0.2: 

![image](https://user-images.githubusercontent.com/43674202/155115254-a8d377b2-0133-4776-b09e-09b12dd2c1d6.png)

**Comment by shuftipro** [comment]
Hi Lennert Defauw,
Kindly use our new SDK in which you will not face any type of conflict.
**https://pub.dev/packages/shuftipro_sdk**
Thanks
