### ISSUE TITLE
Build Not completing

### ISSUE THREAD

**Issue by sawproduction** [shuftipro/Flutter-SDK#3]
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 53s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by shuftipro** [comment]
Greetings,

I wanted to let you know that we've recently updated our SDK and resolved all known issues. We kindly ask you to give it another try, and if you're still experiencing any problems, we would greatly appreciate your feedback.

Thank you.
