### ISSUE TITLE
Build Failed With Exception

### ISSUE THREAD

**Issue by lohitbura07** [shuftipro/Flutter-SDK#4]
Flutter 3.3.0 • channel unknown • unknown source
Framework • revision ffccd96b62 (7 months ago) • 2022-08-29 17:28:57 -0700
Engine • revision 5e9e0e0aa8
Tools • Dart 2.18.0 • DevTools 2.15.0

Error Log - 

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.shuftipro:ShuftiPro_SDK:0.4.8.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/shuftipro/ShuftiPro_SDK/0.4.8/ShuftiPro_SDK-0.4.8.pom
       - https://repo.maven.apache.org/maven2/com/github/shuftipro/ShuftiPro_SDK/0.4.8/ShuftiPro_SDK-0.4.8.pom
       - https://storage.googleapis.com/download.flutter.io/com/github/shuftipro/ShuftiPro_SDK/0.4.8/ShuftiPro_SDK-0.4.8.pom
       - https://jcenter.bintray.com/com/github/shuftipro/ShuftiPro_SDK/0.4.8/ShuftiPro_SDK-0.4.8.pom
       - file:/Users/unthinkble/Library/Android/flutter/.pub-cache/hosted/pub.dartlang.org/shuftipro_sdk-1.2.6/android/libs/ShuftiPro_SDK-0.4.8.jar
       - file:/Users/unthinkble/Library/Android/flutter/.pub-cache/hosted/pub.dartlang.org/shuftipro_sdk-1.2.6/android/libs/ShuftiPro_SDK.jar
     Required by:
         project :app > project :shuftipro_sdk

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by lohitbura07** [comment]
@shuftipro Any Update on this ?

**Comment by shuftipro** [comment]
Greetings,

I wanted to let you know that we've recently updated our SDK and resolved all known issues. We kindly ask you to give it another try, and if you're still experiencing any problems, we would greatly appreciate your feedback.

Thank you.

**Comment by shuftipro** [comment]
> Got any solution?

Greetings,

I wanted to let you know that we've recently updated our SDK and resolved all known issues. We kindly ask you to give it another try, and if you're still experiencing any problems, we would greatly appreciate your feedback.

Thank you.

**Comment by shuftipro** [comment]
> Flutter 3.3.0 • channel unknown • unknown source Framework • revision ffccd96b62 (7 months ago) • 2022-08-29 17:28:57 -0700 Engine • revision 5e9e0e0aa8 Tools • Dart 2.18.0 • DevTools 2.15.0
> 
> Error Log -
> 
> * What went wrong:
>   Execution failed for task ':app:checkDebugAarMetadata'.
> 
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> > Could not find com.github.shuftipro:ShuftiPro_SDK:0.4.8.
> > Searched in the following locations:
> > - https://dl.google.com/dl/android/maven2/com/github/shuftipro/ShuftiPro_SDK/0.4.8/ShuftiPro_SDK-0.4.8.pom
> > - https://repo.maven.apache.org/maven2/com/github/shuftipro/ShuftiPro_SDK/0.4.8/ShuftiPro_SDK-0.4.8.pom
> > - https://storage.googleapis.com/download.flutter.io/com/github/shuftipro/ShuftiPro_SDK/0.4.8/ShuftiPro_SDK-0.4.8.pom
> > - https://jcenter.bintray.com/com/github/shuftipro/ShuftiPro_SDK/0.4.8/ShuftiPro_SDK-0.4.8.pom
> > - file:/Users/unthinkble/Library/Android/flutter/.pub-cache/hosted/pub.dartlang.org/shuftipro_sdk-1.2.6/android/libs/ShuftiPro_SDK-0.4.8.jar
> > - file:/Users/unthinkble/Library/Android/flutter/.pub-cache/hosted/pub.dartlang.org/shuftipro_sdk-1.2.6/android/libs/ShuftiPro_SDK.jar
> > Required by:
> > project :app > project :shuftipro_sdk
> 
> * Try:
> 
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 3s Exception: Gradle task assembleDebug failed with exit code 1

Above issue already fixed please check again.
